project: 
  type: default
  output-dir: reports

format: 
  html:
    embed-resources: true
    theme: 
      dark: darkly
    toc: true
    toc-depth: 5
    toc-expand: true
    crossref: 
      chapters: true
    toc-title: Contents
    code-links: repo
    footnotes-hover: true
    reference-location: section
    execute:
      eval: true
      echo: false
      warning: false
      message: false
    fig-width: 10
    fig-align: center
  
  revealjs:
     theme: default
     embed-resources: true
     width: 1280
     height: 720
     slide-number: true
     math: mathjax
     css: styles.css
     execute:
       eval: true
       echo: false
       warning: false
       message: false
     fig-width: 8
     fig-align: center
     progress: true
     transition: fade
     fig-responsive: true

bibliography: references.bib
cls: harvard-cite-them-right-11th-edition.csl