project: 
  type: default
  output-dir: reports

format: 
  html:
    theme: 
      dark: darkly
    toc: true
    toc-depth: 5
    toc-expand: true
    crossref: 
      chapters: true
    toc-title: Contents
    code-links: repo
    footnotes-hover: true
    reference-location: section
    execute:
      eval: true
      echo: false
      warning: false
    fig-width: 10
    fig-align: center
  
  revealjs:
     theme: default
     css: styles.css
     execute:
       eval: true
       echo: false
       warning: false
     fig-width: 8
     fig-align: center
     progress: true
     font-scale: 90

bibliography: references.bib
cls: harvard-cite-them-right-11th-edition.csl