---
title: "Feature insights into Somalia’s severe acute malnutrition admissions"
subtitle: "A time series analysis spanning from January 2019 to November 2024"
author: "Tomás Zaba"
date: today
format: 
  html:
    theme: 
      dark: darkly
    toc: true
    toc-depth: 3
    toc-expand: true
    toc-title: Contents
    code-links: repo
    execute:
      eval: true
      echo: false
      warning: false
    bibliography: references.bib
    cls: harvard-cite-them-right-11th-edition.csl
    knitr: 
      opts_chunk: 
        collapse: true
        comment: "#>"
---

## Context  
Seasonality significantly impacts the underlying and immediate factors contributing to acute malnutrition (AMN). It refers to recurring patterns within a year [@tsR], such as specific months or quarters when AMN cases rise or fall.  

Understanding the seasonal variation of AMN is crucial for evidence-based decision-making. However, despite a general awareness of its seasonality, limited evidence exists to substantiate it. Consequently, stakeholders often rely on assumptions of a seasonal peak during the food security lean season [@africadry]. To account for this, nutrition surveys are routinely timed to coincide with the lean season each year.

The limited understanding of AMN’s seasonal variation is attributed to two key challenges: (i) the availability of robust analytical methods and (ii) access to primary data [@africadry]. These challenges, however, can be mitigated by leveraging high-quality secondary data, such as survey datasets or treatment program admissions. Studies using 15 years of SMART survey data from African drylands have underscored the complex relationship between AMN and acute food insecurity, revealing that they do not always align across seasons or livelihoods [@africadry; @anastasia]. Notably, this research identified two AMN seasonal peaks: April-May and August-September [@africadry].  

In Somalia, the seasonality of AMN is also generaly associated with that of the food security seasonality. There are five defined food security seasons as described by @ENN:  

```{mermaid}
gantt
    title  Somalia Food Security Seasonal Calendar
    dateFormat M
    axisFormat %b
    todayMarker off
    section Seasons
    Jilaal :1, 4
    Gu     :4, 7
    Post-Gu:7, 8
    Hagaa  :7, 10
    Deyr   :10, 12
```

  + **Jilaal**: the most extended dry season, is characterized by livestock migration and decreased milk production in the pastoralist livelihoods. 
  + **Gu**: characterized by heavy rainfall, it constitutes Somalia's 70% of the crop production season, and livestock production depends upon this season.
  + **Post-Gu**: characterized by increase pasture and water availability for the livestock and increased availability of milk, fruits, vegetables. This is as well the peak season of a liquid butter made of milk know as *ghee*.  
  + **Hagaa**: a dry season, characterized by light rainfalls.  
  + **Deyr**: a rainy season, however localized and less reliable.

It is generally assumed that AMN in Somalia peaks from the end of the Jilaal season to the end of the Hagaa season. An analysis by @ENN, based on SMART surveys conducted by the Food Security and Nutrition Analysis Unit (FSNAU) and partners, with data collected between the Gu and Deyr seasons from 2014 to 2021, identified two distinct seasonal peaks: **May/June (the beginning of Gu)** and **November (mid-Deyr)**, with a decline during the lean season. The study also highlighted variations in these patterns based on livelihood zones, including pastoralist, agro-pastoralist, and riverine/farming communities:

  + Among pastoralist communities, the peak in AMN was observed in June (Gu). This does not align with the food security lean season, as pastoral consumption typically improves starting in April when animals give birth, coinciding with the onset of rainfall. During this period, households gain access to milk and meat and income from the sale of animals. A second peak was noted in November, a period when food insecurity is generally expected to be minimal following the Gu harvest [@ENN].

  + In agropastoralist and farming areas, the seasonality followed the peaks described above [@ENN].

### What does this analysis add?
  This analysis examines six years of severe acute malnutrition (SAM) admission data from treatment programs in Somalia to explore patterns in admissions, focusing on **trends and seasonality** over time.

#### Objectives
  + **Identify and describe trend patterns**: a long-term direction or movement in the admissions that persists across the series. This represents underlying patterns in the admissions after removing short-term fluctuations. 

  + **Identify and describe the seasonality patterns**: recurring patterns that occur in a fixed and specific period every year. 

  + **Quantify the seasonal influences on the admissions**: the extent to which different times of the year impact the number of SAM cases admitted into the treatment program

## Methods
### Data source
The analysis uses [Somalia Nutrition Cluster's](https://response.reliefweb.int/somalia/nutrition) six years and countrywide SAM admission into AMN treatment program. The data is reported monthly, at district level. 

Initially, the analysis was planned to use global acute malnutrition data; however, the Nutrition Cluster advised that, unlike SAM data, moderate acute malnutrition (MAM) data has a variance instability caused by the frequent stockouts of read-to-use supplementary food (RUSF) in the programme. Its use could lead to erroneous findings. Hence, MAM data was excluded from the analysis.


### Data wrangling  
It consisted in excluding districts with missing admissions from January to December; then by summing the total number of children admitted by quarter.
```{mermaid}
flowchart LR
    A[(Dataset)]
    B[Exclusion of districts with consistent missingness of admissions]
    C[Sum the number of SAM cases admitted by **month** and by Region]
    D[Sum the number of SAM cases admitted by **quarter** and by Region]
    E[Time series]

    A --> B --> C --> E
    B --> D --> E
```

::: {.callout-note}
Eight districts were excluded for missingness: Ceel_Dheere, Jalalaqsi, Sablaale, Adan Yabaal, Bu'aale, Jilib, Saakow/Salagle and Sheik
:::

### Analysis techniques  
The analysis process consisted of graphical **exploratory data analysis**, then decomposing the time series into trend, seasonal effects and remainder. Then each component was used to describe furthern its patterns over time. 

The trend component was used to described:

 - The **direction** of the trend along the series:  
      - *upward*: a general increase over time.  
      - *downward*: a general decrease/decay over time.  
      - *flat*: relatively constant over time.
  - The **Shape** of the trend:
      - *Linear trend*: a straight line best fits the data along the series, indicating a constant rate of change over time.
      - *Nonlinear trend*: the trend follows a curved line, indicating acceleration and deceleration of the rate of change.
  - The **Stability** of the trend:
      - *Stable trend*: one that remains consistent over the entire time series.
      - *Changing trend*: one that evolves over time, possibly with abrupt shifts.  

The average rate of change (ARC) of the trend was estimated.

The seasonal component was used to characterized the:  

  - *Amplitute of changes*: when the strength and intensity of the peak or off-season vary over time.  
  - *Phase shifts*: when the timing of the peak season and off-season changes over time.  
  - *Irregular patterns*: when the periodicity of the seasonal patterns are irregular.  

Then a time series regression model was fit to quantify the extent to which different times of the year impact the number of SAM cases admitted into the treatment program.
